name: Summarize and Notify

on:
  push:
    branches:
      - main
      - dev
  pull_request:

jobs:
  summarize:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (ensure enough history)
        uses: actions/checkout@v4
        with:
          fetch-depth: 5

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install reportlab requests

      - name: Run summarizer and reviewer
        run: |
          python3 scripts/summarize_changes.py

      - name: Upload summary artifact
        uses: actions/upload-artifact@v4
        with:
          name: summary
          path: outputs/*.md

      - name: Create issue with summary
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const branch = process.env.GITHUB_REF.replace('refs/heads/','');
            const sha = (process.env.GITHUB_SHA || '').slice(0,7);
            const outPath = `outputs/summary_${branch}_${sha}.md`;
            const body = fs.existsSync(outPath) ? fs.readFileSync(outPath, 'utf8') : "No summary generated.";
            await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `Auto summary — ${branch} @ ${sha}`,
              body
            });

      - name: Send Telegram Notification
        run: |
          python3 scripts/send_telegram.py
        env:
          TELEGRAM_BOT_TOKEN: ${{ '8399179214:AAGjcSbLquG4eopDhXGByLhREdSfULguYgQ' || '' }}
          TELEGRAM_CHAT_ID: ${{'-4908287951' || '' }}
